# Generated by Django 5.0.6 on 2024-07-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tourpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='tourprice',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
