# Generated by Django 5.0.6 on 2024-07-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscribe',
        ),
    ]
