# Generated by Django 5.0.6 on 2024-07-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userdetails',
        ),
    ]
