# Generated by Django 5.0.6 on 2024-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_user_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='tourprice',
        ),
    ]
