# Generated by Django 5.0.6 on 2024-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_tourpackage_tourprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourPackage',
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='tripdescription',
            field=models.TextField(default='null'),
        ),
    ]
