# Generated by Django 5.0.6 on 2024-07-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_trip_image_alter_trip_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='bookings',
        ),
    ]
