# Generated by Django 5.0.6 on 2024-07-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_booking_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='trip',
            new_name='booktrip',
        ),
    ]
