# Generated by Django 5.0.6 on 2024-07-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_trip_bookings_booktrip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
