# Generated by Django 5.0.6 on 2024-07-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_bookings_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='userdetails',
            new_name='user',
        ),
    ]
