# Generated by Django 5.0.6 on 2024-07-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_bookings_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='user',
            new_name='userdetails',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
