# Generated by Django 5.0.6 on 2024-07-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_user_bookings_userdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='userdetails',
            new_name='user',
        ),
    ]
