# Generated by Django 5.0.6 on 2024-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_trip_tripno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tripno',
            field=models.IntegerField(default=1),
        ),
    ]
