# Generated by Django 5.0.6 on 2024-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_trip_tripno'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripid',
            field=models.IntegerField(default=1),
        ),
    ]
