# Generated by Django 5.0.6 on 2024-07-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_trip_tripid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tripid',
        ),
    ]
