# Generated by Django 5.0.6 on 2024-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_trip_tripid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripno',
            field=models.IntegerField(default=1),
        ),
    ]
