# Generated by Django 5.0.6 on 2024-08-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_trip_tripno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trip',
            new_name='trips',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='booktrip',
            new_name='trip',
        ),
    ]
