# Generated by Django 5.0.6 on 2024-08-01 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_rename_trips_trip_rename_trip_bookings_booktrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bookings'),
        ),
    ]
