# Generated by Django 5.0.6 on 2024-08-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_passenger_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
