# Generated by Django 5.0.6 on 2024-08-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
