# Generated by Django 5.0.6 on 2024-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_favourite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=30),
        ),
    ]
