# Generated by Django 5.0.6 on 2024-08-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_review_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='trip',
            new_name='tripname',
        ),
    ]
