# Generated by Django 5.0.6 on 2024-08-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_trip_review_tripname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tripname',
            new_name='reviewtrip',
        ),
    ]
