# Generated by Django 5.0.6 on 2024-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_rename_tripname_review_reviewtrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewtrip',
            new_name='tripname',
        ),
    ]
