# Generated by Django 5.0.6 on 2024-08-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_rename_reviewtrip_review_tripname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tripname',
            new_name='reviewtrip',
        ),
    ]
