# Generated by Django 5.0.6 on 2024-08-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_rename_review_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='passenger',
            new_name='passengers',
        ),
    ]
